import = [
# uncomment the flavour you want below:
#"~/.config/alacritty/catppuccin-latte.toml"
# "~/.config/alacritty/catppuccin-frappe.toml"
    "~/.config/alacritty/catppuccin-macchiato.toml"
# "~/.config/alacritty/catppuccin-mocha.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
dynamic_title = true
option_as_alt = "Both"
opacity = 0.95
blur = true

[window.padding]
x = 5
y = 0
